### PR TITLE
Fix profit table overflow

### LINKED ISSUE #6: BUG: Profits Table Overflow
Summary

When the viewport is less than 1800px, the table on the user commons page overflows in it's container.
Expected Behavior

The profits table should shrink with its container.
Current / Observed Behavior

The table overflows on the common page.

Image

Steps to Reproduce

    Navigate any user commons page
    Shrink your viewport to less than 1800px

### PR DESCRIPTION
**Pull request by awgranados**
In this PR, we changed the table style in order to support horizontal scrolling, and to prevent the table from overflowing.
Before:
Screenshot 2023-05-30 at 3 22 41 PM
After:
Screenshot 2023-05-30 at 3 22 02 PM

Before: https://ucsb-cs156-s23.github.io/proj-happycows-s23-6pm-1/storybook/?path=/story/components-commons-profitstable--emptytable
After: https://ucsb-cs156-s23.github.io/proj-happycows-s23-6pm-1/prs/31/storybook/?path=/story/components-commons-profitstable--emptytable

### CODE REVIEW

**Review by TheRealJBomb — DISMISSED** [review]
LGTM. This is a responsive design fix and also adds the current milk price to this page.

File: frontend/src/main/components/Commons/ManageCows.js [hunk 1]
```diff
@@ -12,6 +12,7 @@ const ManageCows = ({userCommons,commons, onBuy, onSell}) =>  {
             {/* change $10 to info from fixture */}
             <Card.Title>Market Cow Price: ${commons?.cowPrice}</Card.Title>
             <Card.Title>Number of Cows: {userCommons.numOfCows}</Card.Title>
+            <Card.Title>Current Milk Price: ${commons?.milkPrice}</Card.Title>
                 <Row>
                     <Col>
                         <Card.Text>
```
Comment (pconrad) [inline frontend/src/main/components/Commons/ManageCows.js]: This is someone else's PR, right?

That one is blocked waiting on a response to a code review issue, so I can't merge this with this included.

I tested the other change, and it works, so I was ready to merge this until I saw the unrelated changes in ManageCows.js.   

If you can remove that change from this branch, this is mergeable for 5 points.

**Review by pconrad — CHANGES_REQUESTED** [review]
At the time of this code review, there were two commits on this branch separating it from main.

We only want one of those in this PR.

I left a long thread on slack explaining how to cherry pick a branch that has only one of the two commits, and in the process, I made that branch.  It's called `alex-fix-profits-table-v2`

You could do a new PR from that branch.  Or you could use the git reset  and git push -f commands to make the `alex-fix-profits-table` branch (i.e. this PR) point to where the branch `alex-fix-profits-table-v2` points now.  That's how the cool kids do it.

**Comment by awgranados** [comment]
I've removed the edits to ManageCows.js, and there are now only edits that are relevant to the table overflow bug left on this PR.

**Review by mfletcher2 — COMMENTED** [review]
You need to include the storybook links in the description https://ucsb-cs156-s23.slack.com/archives/C050779M19P/p1685400785702049

**Review by mfletcher2 — APPROVED** [review]
LGTM

**Review by briggsrrr — APPROVED** [review]
LGTM 🚀  

Tested on QA.
